[DBZ-PGYB] Changes to support LSN types with replication slot
yugabyte/debezium pull request #162
Opened 2024-10-16 05:04 UTC by vaibhav-yb

2024-11-27 17:02 UTC, suranjan requested changes

2024-11-27 17:02 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +                    lsn = walPosition.getLastCommitStoredLsn() != null ? walPosition.getLastCommitStoredLsn() : lastSentFeedback;
comment the logic/reasoning

2025-01-20 11:58 UTC, suranjan requested changes

2025-01-20 11:58 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +                if (connectorConfig.slotLsnType().isSequence()) {
Deduplicate...just write a method to get the lsn based on type.
explain why are we setting lastSentFeedback

2025-01-20 11:58 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +                    LOGGER.info("Resume LSN is null");
when is this possible? Please out comment

2025-01-20 11:58 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +                LOGGER.info("Adding '{}' as lsn to the commit times queue", Lsn.valueOf(lsn.asLong() - 1));
Info?

2025-01-20 11:58 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +            LOGGER.info("Received offset commit request on commit LSN '{}' and change LSN '{}'", commitLsn, changeLsn);
All these info is for debugging now otherwise it will create lots of logs

2025-01-20 11:58 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +    protected Lsn getLsnToBeFlushed(Lsn lsn) {
explain the logic..

2025-01-20 17:57 UTC, vaibhav-yb commented
@suranjan There are certain logs that I have kept for the debugging runs, I will ensure to remove/convert them back to DEBUG before merging this.

2025-02-05 07:17 UTC, suranjan requested changes

2025-02-05 07:17 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +                    Lsn lastStoredLsn = connectorConfig.slotLsnType().isHybridTime() ? walPosition.getLastCommitStoredLsn() : walPosition.getLastEventStoredLsn();
Comment the logic

2025-02-05 07:17 UTC, suranjan commented on debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresStreamingChangeEventSource.java
> +        LOGGER.info("Queue at this time: {}", commitTimes);
info or debug?

2025-02-05 10:06 UTC, suranjan approved these changes

2025-02-05 16:23 UTC, merged