Patch to log the number of records in a transactional block
yugabyte/debezium pull request #28
Opened 2022-05-23 04:18 UTC by vaibhav-yb

2022-05-23 04:19 UTC, vaibhav-yb commented on debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
> +                                            LOGGER.info("Records in the transactional block for tablet {}: {}", tabletId, recordsInTransactionalBlock.get(tabletId));
Make this a `LOGGER.debug()` statement.

2022-05-23 04:20 UTC, vaibhav-yb commented on debezium-connector-yugabytedb2/pom.xml
> +            <version>0.8.15-SNAPSHOT</version>
Using this version number, create a release for `2.12.4.1-b2` and another release for the latest master of `yugabyte-db`

2022-05-23 05:57 UTC, suranjan requested changes
Ideally we can use just one map and contains method to see if the begin record has come.
In begin:
recordsInTransactionalBlock.put(tabletId, 0)
in dml record
if( recordsInTransactionalBlock.contains(tabletId)
recordsInTransactionalBlock.merge(tabletId, 1, Integer::sum)
//warning if it doesn't contain ..ideally that shouldn't be the case?

2022-05-23 05:57 UTC, suranjan commented on debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
> +                                                LOGGER.info("Records in the transactional block for tablet {}: {}", tabletId, recordsInTransactionalBlock.get(tabletId));
At info level there will be too much logs. Most of the time there will be single record transaction.

2022-05-27 08:56 UTC, suranjan approved these changes
Looks good.

2022-05-27 08:56 UTC, suranjan commented on debezium-connector-yugabytedb2/src/main/java/io/debezium/connector/yugabytedb/YugabyteDBStreamingChangeEventSource.java
> +        if (term == -1 && index == -1) {
We don't have the change for -1,-1 OpId in final-connector?

2022-05-30 17:28 UTC, merged